# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes

ZSH_THEME="powerlevel10k/powerlevel10k"
DEFAULT_USER=$(whoami)

POWERLEVEL9K_PROMPT_ON_NEWLINE=false
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_from_right
POWERLEVEL9K_DIR_SHOW_WRITABLE=true

POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=4
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=1

POWERLEVEL9K_TIME_FOREGROUND='grey74'
POWERLEVEL9K_TIME_BACKGROUND='grey7'

POWERLEVEL9K_KUBECONTEXT_FOREGROUND='grey74'
POWERLEVEL9K_KUBECONTEXT_BACKGROUND='grey7'

POWERLEVEL9K_VCS_CLEAN_FOREGROUND='darkgreen'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='grey7'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='grey7'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='darkred'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='grey7'

POWERLEVEL9K_DIR_HOME_BACKGROUND='grey74'
POWERLEVEL9K_DIR_HOME_FOREGROUND='grey7'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='grey7'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='grey74'
POWERLEVEL9K_DIR_ETC_BACKGROUND='darkred'
POWERLEVEL9K_DIR_ETC_FOREGROUND='grey74'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='grey7'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='grey74'
POWERLEVEL9K_DIR_ANCHOR_BOLD=true

POWERLEVEL9K_STATUS_OK_FOREGROUND='grey7'
POWERLEVEL9K_STATUS_OK_BACKGROUND='darkgreen'
POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND='grey7'
POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND='darkgreen'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='darkred'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='grey7'
POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND='darkred'
POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND='grey7'
POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND='darkred'
POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND='grey7'

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(kubecontext status command_execution_time)
